#!/usr/bin/env sh

HELP1='help'
HELP2='-h'
HELP3='--help'

if [ "$1" == $HELP1 ] || [ "$1" == $HELP2 ] || [ "$1" == $HELP3 ]; then
    echo "Usage:";
    echo "  $0";
    echo "  $0 [help | -h | --help]";
    echo "  HOST=<host> $0";
    echo "  HOST=<host> DATABASE=<database> $0";
    echo "  HOST=<host> DATABASE=<database> VERSION=<version> $0";
    exit 0;
fi


function ensure_file {
    if [ ! -f "$1" ]
    then
        local msg="File does not exist: $1";
        [ "$2" ] && local msg=$2;
        echo $msg;
        exit 1;
    fi
}

[ "$HOST" ] || HOST=localhost
[ "$DATABASE" ] || DATABASE=pooldin
[ "$VERSION" ] || VERSION=a4

BEGIN=sql/begin.sql
SCHEMA=sql/$VERSION/schema.sql
TYPES=sql/$VERSION/types.sql
ALL=sql/$VERSION/all.sql
COMMIT=sql/commit.sql

ensure_file "$BEGIN"
ensure_file "$SCHEMA"
ensure_file "$TYPES"
ensure_file "$ALL"
ensure_file "$COMMIT"

cat $BEGIN $SCHEMA $TYPES $ALL $COMMIT | psql -h "$HOST" -d "$DATABASE"
